### ISSUE TITLE
Request "backup"

### ISSUE THREAD

**Issue by laggis** [M0RG4N01/TCAdminMySqlModule#4]
Hey can you add so the person can press backup databasen and they can download it or be saved in a loction where they can press restore or something. Sorry might be a stuipid thing to have but many of my clients wants that and that will help them a lot

**Comment by M0RG4N01** [comment]
Hey, 

Thanks for the request, i'm sure that I can work on that. I already have the methods for backup and restore created for when a service is moved so I can definitely use them with some buttons on the manager page hopefully :)

**Comment by laggis** [comment]
Sounds great:)

**Comment by M0RG4N01** [comment]
Backup has been implemented in 1.0.7
I will be working on restore now 👍

**Comment by laggis** [comment]
Hey saw that you update it i have the download button but when i press it its just a black screen and saying

"TCAdmin.Ajax.ShowBasicDialog('Error', 'Uh oh, something went wrong! Please contact an Administrator (see web console for details)!');console.log('Specified argument was out of the range of valid values.\nParameter name: UserId (0)');$('body').css('cursor', 'default');"

**Comment by M0RG4N01** [comment]
@laggis Issue should be resolved if you reinstall 1.0.7, the issue was that a user could not create a new object so I had to implement the skip security check so that it could be done 👍

**Comment by laggis** [comment]
> @laggis Issue should be resolved if you reinstall 1.0.7, the issue was that a user could not create a new object so I had to implement the skip security check so that it could be done 👍

Works perfect after reinstall:)

**Comment by M0RG4N01** [comment]
Restore functionality has been added :)
