### ISSUE TITLE
Cannot save any TCA Datacenter or Server config, "Unknown column 'mysqlplugin_ip' in 'field list'"

### ISSUE THREAD

**Issue by Daren-42** [M0RG4N01/TCAdminMySqlModule#7]
Getting the following error when trying to save Datacenter and/or Server configuration:
Unknown column 'mysqlplugin_ip' in 'field list'

I have uninstalled and reinstalled the modules.

I have restarted the monitors on all of the servers.

I cannot seem to get past this error.
Running TCAdmin 2.0.158 on Windows Server 2019.

 

Any ideas?

**Comment by M0RG4N01** [comment]
Hey! 

This is an issue with TCAdmin, you will need to open a ticket and they will send you the sql commands you need for the missing columns 👍 

Heres the link to submit a ticket: https://clients.tcadmin.com/billing/submitticket.php
