### ISSUE TITLE
caant Delete Database

### ISSUE THREAD

**Issue by numpty9989** [M0RG4N01/TCAdminMySqlModule#9]
i created a test DB for one of my master  servers and I am unable to delete it pleas help me resolve this the login info is correct for the MySQL server

**Comment by numpty9989** [comment]
i fixed it by removing the info in the database now I'm met with this... i have triple checked the database login information and its correct https://i.imgur.com/dNIAg30.png

**Comment by IanDHH** [comment]
I've also encountered this issue.

**Comment by M0RG4N01** [comment]
When you see that error, open the browser web console so we can see more details on why the error is happening:

![image](https://user-images.githubusercontent.com/19923469/115229477-02e1d980-a10b-11eb-8e26-d1d17426742b.png)
